version: 0.0
os: linux
files:
  - source: .
    destination: /home/ubuntu/scholarly
hooks:
  BeforeInstall:
    - location: backend/scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
  afterInstall:
    - location: backend/scripts/restart_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStart:
    - location: backend/scripts/start_server.sh
      timeout: 300
      runas: ubuntu
  ApplicationStop:
    - location: backend/scripts/stop_server.sh
      timeout: 300
      runas: ubuntu
