version: 0.0
os: linux
files:
  - source: "."
    destination: /home/ubuntu/scholarly/backend
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies
      timeout: 300
      runas: ubuntu
