version: 0.0
os: linux
files:
  - source: "backend/"
    destination: /home/ubuntu/scholarly/backend
hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu
